# Generated by Django 3.2.6 on 2021-10-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, null=True)),
                ('context', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_package', models.CharField(max_length=150, null=True)),
                ('cost', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('condition', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='proofDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameWhoDonate', models.CharField(max_length=150, null=True)),
                ('Howmuch', models.IntegerField(null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
