# Generated by Django 3.2.6 on 2021-10-26 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100, null=True)),
                ('Last_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('Doctor_id', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100, null=True)),
                ('Last_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('Patient_id', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='proofdonation',
            old_name='date',
            new_name='dateDonate',
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(max_length=100, null=True)),
                ('Doctor_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors')),
                ('Patient_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('Patient_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.patients')),
                ('name_package', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.package')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100, null=True)),
                ('dateapp', models.DateTimeField(null=True)),
                ('Doctor_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors')),
                ('Patient_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.patients')),
            ],
        ),
    ]
