# Generated by Django 3.2.6 on 2021-10-26 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0002_auto_20211026_2239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
        migrations.RenameModel(
            old_name='Specialities',
            new_name='Specialitie',
        ),
        migrations.RenameField(
            model_name='proofdonation',
            old_name='nameWhoDonate',
            new_name='First_nameWhoDonate',
        ),
        migrations.AddField(
            model_name='article',
            name='Doctor_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='package',
            name='Patient_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.patient'),
        ),
        migrations.AddField(
            model_name='proofdonation',
            name='Last_nameWhoDonate',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
