# Generated by Django 3.2.7 on 2021-11-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
    ]
