# Generated by Django 3.2.7 on 2021-11-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_rename_article_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'get_latest_by': 'datetime_post'},
        ),
        migrations.AddField(
            model_name='articles',
            name='datetime_post',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
