# Generated by Django 3.2.7 on 2021-11-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_auto_20211104_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='datetime_post',
        ),
    ]
