# Generated by Django 3.2.6 on 2021-11-05 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0009_auto_20211104_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, null=True)),
                ('context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, null=True)),
                ('context', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Doctor_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Patient_id',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='Doctor_id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='Doctor_id',
        ),
        migrations.DeleteModel(
            name='proofDonation',
        ),
        migrations.RemoveField(
            model_name='specialitie',
            name='Doctor_id',
        ),
        migrations.RemoveField(
            model_name='specialitie',
            name='Patient_id',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Last_name',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='Patient_id',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='name_package',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Doctor_id',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Patient_id',
        ),
        migrations.RemoveField(
            model_name='package',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='name_package',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Patient_id',
        ),
        migrations.AddField(
            model_name='buy',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='buy',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.package'),
        ),
        migrations.AddField(
            model_name='buy',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultpic.jpeg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='package',
            name='cond',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='package',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='status',
            field=models.CharField(choices=[('NOT PAID', 'NOT PAID'), ('PAID', 'PAID')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultpic.jpeg', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Specialitie',
        ),
        migrations.AddField(
            model_name='new',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='article',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
