# Generated by Django 3.2.6 on 2021-11-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_auto_20211105_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
