# Generated by Django 3.2.6 on 2021-11-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_doctor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='First_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='First_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
