# Generated by Django 3.2.6 on 2021-11-05 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_auto_20211105_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='new',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
