# Generated by Django 3.2.6 on 2021-11-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_package_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='defbg.png', null=True, upload_to='images/articles'),
        ),
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.ImageField(default='defbg.png', null=True, upload_to='images/news'),
        ),
        migrations.AlterField(
            model_name='package',
            name='img',
            field=models.ImageField(default='defbg.png', null=True, upload_to='images/packages'),
        ),
    ]
