# Generated by Django 3.2.6 on 2021-11-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0017_auto_20211107_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(null=True, upload_to='images/articles'),
        ),
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.ImageField(null=True, upload_to='images/news'),
        ),
        migrations.AlterField(
            model_name='package',
            name='img',
            field=models.ImageField(null=True, upload_to='images/packages'),
        ),
    ]
