# Generated by Django 3.2.6 on 2021-11-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_auto_20211107_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='img',
            field=models.ImageField(default='pic.jpg', null=True, upload_to=''),
        ),
    ]
