# Generated by Django 3.2.6 on 2021-11-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0019_alter_package_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='pic.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.ImageField(default='pic.jpg', null=True, upload_to=''),
        ),
    ]
