# Generated by Django 3.2.7 on 2021-11-09 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_auto_20211107_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=100, null=True)),
                ('dateapp', models.DateTimeField(null=True)),
                ('Doctor_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('Patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.patient')),
            ],
        ),
    ]
