# Generated by Django 3.2.7 on 2021-11-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0021_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
