# Generated by Django 3.2.7 on 2021-11-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0024_auto_20211111_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='spec',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Specialitie',
        ),
    ]
