# Generated by Django 3.2.6 on 2021-11-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0026_alter_doctor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
