# Generated by Django 3.2.7 on 2021-11-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0026_alter_doctor_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='person.jpg', null=True, upload_to=''),
        ),
    ]
