# Generated by Django 3.2.6 on 2021-11-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0027_buy_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='img',
            field=models.ImageField(default='nopic.png', null=True, upload_to=''),
        ),
    ]
