# Generated by Django 3.2.7 on 2021-11-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0027_alter_doctor_profile_pic'),
        ('doctors', '0028_alter_buy_img'),
    ]

    operations = [
    ]
